{{- if .Values.managedServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount }}-cluster-role  # serviceAccount 값에 맞게 변경
  labels:
    app: "{{ template "metricbeat.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
rules:
  {{ toYaml .Values.clusterRoleRules | nindent 2 }}  # values.yaml에서 설정한 규칙을 가져옴
{{- end }}

