replicaCount: 1

image:
  repository: chamchimayo/mcp-inbound
  tag: "1.0.2"
  pullPolicy: IfNotPresent

service:
  name: mcp-inbound
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: api.sol-wms.store
      paths:
        - path: /api/mcp-inbound(/|$)(.*)
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - api.sol-wms.store
      secretName: letsencrypt-cert
