apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inbound-kong-ingress
  namespace: wms
  annotations:
    kubernetes.io/ingress.class: "kong"  # Kong Ingress Controller로 처리
    konghq.com/strip-path: "true"        # /api/inbound → / 내부 서비스로 전달
spec:
  rules:
    - host: api.sol-wms.store
      http:
        paths:
          - path: /api/inbound
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.service.port }}