apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mcp-inbound
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mcp-inbound
  template:
    metadata:
      labels:
        app: mcp-inbound
    spec:
      containers:
        - name: mcp-inbound
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: mcp-inbound-secret
