daemonset:
  enabled: true
  env:
    - name: NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
deployment:
  enabled: false
automountServiceAccountToken: true
setup:
  dashboards:
    enabled: true
  kibana:
    host: "http://195.168.9.237:5601"
metricbeatConfig:
  metricbeat.yml: |
    metricbeat.modules:
      - module: kubernetes
        enabled: true
        metricsets:
          - state_node
          - state_deployment
          - state_replicaset
          - state_statefulset
          - state_pod
          - state_container
        period: 10s
        hosts: ["http://kube-state-metrics.metricbeat.svc.cluster.local:8080"]
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        add_metadata: true

      - module: kubernetes
        enabled: true
        metricsets:
          - node
          - pod
          - container
          - volume
          - system
        period: 10s
        hosts: ["https://${NODE_IP}:10250"]
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        ssl.verification_mode: "none"
        add_metadata: true

      - module: system
        enabled: true
        period: 10s
        metricsets:
          - cpu
          - load
          - memory
          - network
          - process
          - process_summary
          - uptime
          - diskio
        processes: ['.*']
        process.include_top_n:
          by_cpu: 5
          by_memory: 5

    processors:
      - add_fields:
          target: fields
          fields:
            beat_type: metricbeat

    output.logstash:
      hosts: ["195.168.9.181:5044"]

elasticsearch:
  enabled: false

securityContext:
  runAsUser: 0
  runAsGroup: 0
  privileged: true

podSecurityContext:
  fsGroup: 0

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

managedServiceAccount: true
serviceAccount: "metricbeat"

rbac:
  create: true
  clusterRole:
    create: true
  clusterRoleBinding:
    create: true
    subjects:
      - kind: ServiceAccount
        name: metricbeat
        namespace: metricbeat

clusterRoleRules:
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - pods
      - events
      - nodes/stats
      - nodes/metrics
      - nodes/proxy
      - nodes/log
      - pods/log
      - configmaps
      - secrets
      - persistentvolumes
      - persistentvolumeclaims
      - replicationcontrollers
      - resourcequotas
      - services
      - limitranges
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs: ["get", "list", "watch"]

  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]

  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs: ["get", "list", "watch"]

  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
      - volumeattachments
    verbs: ["get", "list", "watch"]

  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs: ["get", "list", "watch"]

  - apiGroups: ["certificates.k8s.io"]
    resources:
      - certificatesigningrequests
    verbs: ["get", "list", "watch"]

  - apiGroups: ["metrics.k8s.io"]
    resources:
      - nodes
      - pods
    verbs: ["get", "list", "watch"]

  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch"]

image: "docker.elastic.co/beats/metricbeat"
imageTag: "8.5.1"
imagePullPolicy: "IfNotPresent"

livenessProbe:
  exec:
    command:
      - sh
      - -c
      - |
        #!/usr/bin/env bash -e
        metricbeat test output
  initialDelaySeconds: 30
  periodSeconds: 30

readinessProbe:
  exec:
    command:
      - sh
      - -c
      - |
        #!/usr/bin/env bash -e
        metricbeat test output
  initialDelaySeconds: 20
  periodSeconds: 30

kube_state_metrics:
  enabled: false

