apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: kong
data:
  kong.yml: |
    _format_version: "3.0"

    services:
      - name: inventory-service
        url: http://inventory-service.wms.svc.cluster.local:1050
        routes:
          - name: inventory-api
            paths:
              - /api/inventory

      - name: user-service
        url: http://user-service.wms.svc.cluster.local:1040
        routes:
          - name: user-api
            paths:
              - /api/user

      - name: inbound-service
        url: http://inbound-service.wms.svc.cluster.local:1050
        routes:
          - name: inbound-api
            paths:
              - /api/inbound
            strip_path: false 

# plugins:
#   - name: jwt
#     config:
#       key_claim_name: "iss"
#       secret_is_base64: false
