{{- if .Values.ingressController.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: kong
  annotations:
    ingressclass.kubernetes.io/is-default-class: "false"
spec:
  controller: konghq.com/ingress-controller
{{- end }}
